
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VPaned vpaned1;

	private global::Gtk.HPaned hpaned1;

	private global::Gtk.VPaned vpaned4;

	private global::Gtk.HPaned hpaned4;

	private global::Gtk.ComboBoxEntry taskCombobox;

	private global::Gtk.Label time;

	private global::Gtk.ComboBox timeCombobox;

	private global::Gtk.Button startButton;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView treeview1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vpaned1 = new global::Gtk.VPaned();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 88;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.hpaned1 = new global::Gtk.HPaned();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 522;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vpaned4 = new global::Gtk.VPaned();
		this.vpaned4.CanFocus = true;
		this.vpaned4.Name = "vpaned4";
		this.vpaned4.Position = 36;
		// Container child vpaned4.Gtk.Paned+PanedChild
		this.hpaned4 = new global::Gtk.HPaned();
		this.hpaned4.CanFocus = true;
		this.hpaned4.Name = "hpaned4";
		this.hpaned4.Position = 412;
		// Container child hpaned4.Gtk.Paned+PanedChild
		this.taskCombobox = global::Gtk.ComboBoxEntry.NewText();
		this.taskCombobox.Name = "taskCombobox";
		this.hpaned4.Add(this.taskCombobox);
		global::Gtk.Paned.PanedChild w1 = ((global::Gtk.Paned.PanedChild)(this.hpaned4[this.taskCombobox]));
		w1.Resize = false;
		// Container child hpaned4.Gtk.Paned+PanedChild
		this.time = new global::Gtk.Label();
		this.time.Name = "time";
		this.time.LabelProp = global::Mono.Unix.Catalog.GetString("00:00:00");
		this.hpaned4.Add(this.time);
		this.vpaned4.Add(this.hpaned4);
		global::Gtk.Paned.PanedChild w3 = ((global::Gtk.Paned.PanedChild)(this.vpaned4[this.hpaned4]));
		w3.Resize = false;
		// Container child vpaned4.Gtk.Paned+PanedChild
		this.timeCombobox = global::Gtk.ComboBox.NewText();
		this.timeCombobox.Name = "timeCombobox";
		this.vpaned4.Add(this.timeCombobox);
		this.hpaned1.Add(this.vpaned4);
		global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.vpaned4]));
		w5.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.startButton = new global::Gtk.Button();
		this.startButton.CanFocus = true;
		this.startButton.Name = "startButton";
		this.startButton.UseUnderline = true;
		this.startButton.Label = global::Mono.Unix.Catalog.GetString("Start");
		this.hpaned1.Add(this.startButton);
		this.vpaned1.Add(this.hpaned1);
		global::Gtk.Paned.PanedChild w7 = ((global::Gtk.Paned.PanedChild)(this.vpaned1[this.hpaned1]));
		w7.Resize = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeview1 = new global::Gtk.TreeView();
		this.treeview1.CanFocus = true;
		this.treeview1.Name = "treeview1";
		this.GtkScrolledWindow.Add(this.treeview1);
		this.vpaned1.Add(this.GtkScrolledWindow);
		this.Add(this.vpaned1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 649;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.startButton.Clicked += new global::System.EventHandler(this.OnStartButtonClicked);
	}
}
